# Generated by Django 3.1.1 on 2020-10-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'core_district',
            },
        ),
        migrations.CreateModel(
            name='DistrictLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'core_district_level',
            },
        ),
        migrations.CreateModel(
            name='ProvinceLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'core_province_level',
            },
        ),
        migrations.CreateModel(
            name='WardsLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'core_wards_level',
            },
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district')),
                ('wards_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wardslevel')),
            ],
            options={
                'db_table': 'core_wards',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('province_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provincelevel')),
            ],
            options={
                'db_table': 'core_province',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='district_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.districtlevel'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province'),
        ),
    ]
