# Generated by Django 3.1.1 on 2020-10-15 13:16
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals
from django.db import migrations
from aznose.settings import PROJECT_DIR
import os


def load_core_address_from_sql():
    #from aznose.settings import PROJECT_DIR
    #import os
    sql_statements = open(os.path.join(
        PROJECT_DIR, 'core/sql/core.sql'), 'r', encoding='utf8').read()
    return sql_statements


def delete_core_address_with_sql():
    sql_statements = open(os.path.join(
        PROJECT_DIR, 'core/sql/core_reverse.sql'), 'r', encoding='utf8').read()
    return sql_statements


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_core_address_from_sql(),
                          delete_core_address_with_sql()),
    ]
