# Generated by Django 3.1.1 on 2020-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_color',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
