# Generated by Django 3.1.1 on 2020-10-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201004_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_color',
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
