# Generated by Django 3.1.1 on 2020-11-06 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_auto_20201025_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_all_day',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='appointment',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('modified_date', models.DateTimeField()),
                ('freq_type', models.IntegerField(choices=[(1, 'Once'), (4, 'Daily'), (8, 'Weekly'), (16, 'Monthly')], null=True)),
                ('freq_interval', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (4, 'Tuesday'), (8, 'Wednesday'), (16, 'Thursday'), (32, 'Firday'), (64, 'Saturday')], null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_created_user', to=settings.AUTH_USER_MODEL)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
