# Generated by Django 3.1.1 on 2020-11-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20201107_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='to_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='from_date',
            new_name='start_date',
        ),
    ]
