# Generated by Django 3.1.1 on 2020-11-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20201107_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
