# Generated by Django 3.1.1 on 2020-11-11 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_auto_20201110_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='modiefied_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='modified_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_modified_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
