# Generated by Django 3.1.1 on 2020-11-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20201111_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Tiềm năng'), (1, 'Khách hàng')], default=0),
        ),
    ]
