# Generated by Django 3.1.1 on 2020-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20201203_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='customer',
        ),
        migrations.AddField(
            model_name='task',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='client_type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
