# Generated by Django 3.1.1 on 2020-12-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20201210_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client_type',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
