# Generated by Django 3.1.1 on 2020-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20201210_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
