# Generated by Django 3.1.1 on 2020-12-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0018_auto_20201212_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'crm_activity_type',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityId', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('RegardingObjectId', models.IntegerField(blank=True, null=True)),
                ('RegardingObjectTypeCode', models.CharField(blank=True, max_length=128, null=True)),
                ('client_id', models.IntegerField()),
                ('client_type', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('ActivityType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.activitytype')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_Activity',
            },
        ),
    ]
