# Generated by Django 3.1.1 on 2020-12-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_activity_activitytype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='crm_activity',
        ),
    ]
