# Generated by Django 3.1.1 on 2020-12-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20201225_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_id',
        ),
    ]
