# Generated by Django 3.1.1 on 2021-06-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_lead_leadstatuscode_leadtimeframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='decision_maker',
            new_name='authority',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='decision_timeframe',
            new_name='timeframe',
        ),
    ]
