# Generated by Django 3.1.1 on 2021-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_staffgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTittle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
