# Generated by Django 3.1.1 on 2021-11-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_jobtittle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTittle',
            new_name='JobTitle',
        ),
    ]
