# Generated by Django 3.1.1 on 2021-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20211105_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
