# Generated by Django 3.1.1 on 2021-11-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_staff_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobtitle',
            table='crm_job_title',
        ),
    ]
