# Generated by Django 3.1.1 on 2021-11-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_auto_20211114_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
